
<body>
<?php
               /**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
                $access_key = "&appid=bf0ab26444debc110859a739f7963f55&units=metric";
                $ip_obj = $block->sendJsontoServer();
                $country = $ip_obj->country_name;
                $region = $ip_obj->region_name;
                if(!$region){
                    $region = $ip_obj->location->capital;
                }
                $current_obj = $block->getCurrentData($region, $country, $access_key);
                $city_id = $current_obj->id;
                $forcast_obj = $block->getForcast($city_id, $access_key);
            ?>
    <style>
        .weather-side {
    position: relative;
    height: 100%;
    border-radius: 25px;
   margin-bottom :25px;
    background-image: url("https://images.unsplash.com/photo-1559963110-71b394e7494d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80");
    width: 300px;
    -webkit-box-shadow: 0 0 20px -10px rgba(0, 0, 0, 0.2);
            box-shadow: 0 0 20px -10px rgba(0, 0, 0, 0.2);
    -webkit-transition: -webkit-transform 300ms ease;
    transition: -webkit-transform 300ms ease;
    -o-transition: transform 300ms ease;
    transition: transform 300ms ease;
    transition: transform 300ms ease, -webkit-transform 300ms ease;
    -webkit-transform: translateZ(0) scale(1.02) perspective(1000px);
            transform: translateZ(0) scale(1.02) perspective(1000px);
    float: left;
}

.weather-side:hover {
    -webkit-transform: scale(1.1) perspective(1500px) rotateY(10deg);
            transform: scale(1.1) perspective(1500px) rotateY(10deg);
}

.info-side {
    position: relative;
    float: left;
    height: 445px;
    padding-top: 25px;
    margin-bottom :25px;
    margin-left :7px;
    display: block;
    position: relative;
    border-radius: 25px;

    background-image: url("https://zicxa.com/hinh-anh/wp-content/uploads/2019/06/H%C3%ACnh-%E1%BA%A3nh-b%E1%BA%A7u-tr%E1%BB%9Di-xanh-tuy%E1%BB%87t-%C4%91%E1%BA%B9p-full-HD-1.jpg");
    
    -webkit-transition: -webkit-transform 300ms ease;
    transition: -webkit-transform 300ms ease;
    -o-transition: transform 300ms ease;
    transition: transform 300ms ease;
    transition: transform 300ms ease, -webkit-transform 300ms ease;
    -webkit-transform: translateZ(0) scale(1.02) perspective(1000px);
            transform: translateZ(0) scale(1.02) perspective(1000px);
    float: left;
}
.info-side:hover {
    -webkit-transform: scale(1.08) perspective(1500px) rotateY(10deg);
            transform: scale(1.08) perspective(1500px) rotateY(10deg);
}
.today-info {
    padding: 15px;
    margin: 0 25px 25px 25px;
  /*box-shadow: 0 0 50px -5px rgba(0, 0, 0, 0.25); */
    border-radius: 10px;
}


.today-info>div .title {
    margin-left :10px;
   
    font-weight: 600;
}

#vpre {
    padding-left :70px;

}

#vhum {
    padding-left :80px;

}
#vwin {
    padding-left :50px;

}
.week-list>li {
    float: left;
    padding: 15px;
    cursor: pointer;
    -webkit-transition: 200ms ease;
    -o-transition: 200ms ease;
    transition: 200ms ease;
    border-radius: 10px;
}

.week-list>li .day-name {
    display: block;
    margin: 10px 0 0 0;
    text-align: center;
}
.week-list>li:hover {
    -webkit-transform: scale(1.1);
        -ms-transform: scale(1.1);
            transform: scale(1.1);
    background: #fff;
    color: #222831;
    -webkit-box-shadow: 0 0 40px -5px rgba(0, 0, 0, 0.2);
            box-shadow: 0 0 40px -5px rgba(0, 0, 0, 0.2)
}

.week-list {
  
    list-style-type: none;
    padding: 0;
    margin: 10px 35px;
    -webkit-box-shadow: 0 0 50px -5px rgba(0, 0, 0, 0.25);
            box-shadow: 0 0 50px -5px rgba(0, 0, 0, 0.25);
    border-radius: 10px;
   
}

.week-list>li .day-icon {
    display: block;
    height: 30px;
    width: auto;
    margin: 0 auto;
}
h1{
   color : black;
   font-weight:400;
 }
    </style>
    <h1>Thời tiết</h1>
    <div class="container">
        <div class="weather-side">
            <div class="weather-gradient"></div>
            <div class="date-container">
                <h2 class="date-dayname">THỜI GIAN CẬP NHẬT</h2><span class="date-day">
                    <?php echo date("d/m/Y H:i:s",$current_obj->dt); ?>
                  
                </span>
            
                   <div class="location-icon" data-feather="map-pin">
                       <img src=" <?php echo $ip_obj->location->country_flag ?>" alt="" class="country_flag"> 
                 </div> 
                        <span class="location">
                             <p><?php echo $region.", ".$country ?></p>
                        </span>   
                </div>
                
            <div class="weather-container"><i class="weather-icon" data-feather="sun"></i>
                <h1 class="weather-temp"> <?php echo $current_obj->main->temp."℃" ?></h1>
                <h3 class="weather-desc">  <?php $date=getdate();
                    echo $date['weekday'];?></h3>
            </div>
        </div>
        <div class="info-side" >
            <div class="today-info-container" >
                <div class="today-info">
                    <div class="precipitation"> <span class="title">ÁP SUẤT</span><span class="value" id ="vpre"><?php echo $current_obj->main->pressure?> %</span>
                        <div class="clear"></div>
                    </div>
                    <div class="humidity"> <span class="title">ĐỘ ẨM</span><span class="value" id="vhum"> <?php echo $current_obj->main->humidity."%" ?></span>
                        <div class="clear"></div>
                    </div>
                    <div class="wind"> <span class="title">TỐC ĐỘ GIÓ</span><span class="value" id ="vwin"><?php echo $current_obj->wind->speed." meter/sec" ?></span>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <?php 
            switch($date['weekday']){
                case"Sunday":
                    $day1 = "Mon";
                    $day2 = "Tue";
                    $day3 = "Wed";
                    $day4 = "Thu";
                break;
                case"Monday":
                    $day1 = "Tue";
                    $day2 = "Wed";
                    $day3 = "Thu";
                    $day4 = "Fri";
                break;
                case"Tuesday":
                    $day1 = "Wed";
                    $day2 = "Thu";
                    $day3 = "Fri";
                    $day4 = "Sat";
                break;
                case"Wednesday":
                    $day1 = "Thu";
                    $day2 = "Fri";
                    $day3 = "Sat";
                    $day4 = "Sun";
                break;
                case"Thursday":
                    $day1 = "Fri";
                    $day2 = "Sat";
                    $day3 = "Sun";
                    $day4 = "Mon";
                break;
                case"Friday":
                    $day1 = "Sat";
                    $day2 = "Sun";
                    $day3 = "Mon";
                    $day4 = "Tue";
                break;
                case"Saturday":
                    $day1 = "Sun";
                    $day2 = "Mon";
                    $day3 = "Tue";
                    $day4 = "Wed";
                break;
            }
                       
            ?>
            <div class="week-container" >
                <ul class="week-list">
                    <li  class="active"><i class="day-icon" data-feather="sun"></i><span class="day-name"><?php echo $day1 ?></span><span class="day-temp">29°C</span></li > 
                    <li><i class="day-icon" data-feather="cloud"></i><span class="day-name"><?php echo $day2 ?></span><span class="day-temp">31°C</span></li>
                    <li><i class="day-icon" data-feather="cloud-snow"></i><span class="day-name"><?php echo $day3 ?></span><span class="day-temp">28°C</span></li>
                    <li><i class="day-icon" data-feather="cloud-rain"></i><span class="day-name"><?php echo $day4 ?></span><span class="day-temp">29°C</span></li>
                    <div class="clear"></div> 
                </ul>
            </div>
        
        </div>
    </div>
</body>
</html>